### ISSUE TITLE
Compatibility with MediaWiki 1.35

### ISSUE THREAD

**Issue by markus-96** [ProfessionalWiki/SubPageList#72]
### Setup

- MediaWiki version: 1.35.10 (BlueSpice 4.3)
- PHP version: 8.0.27
- Database and version (MySQL etc.): mariadb 15.1
- SubPageList version: 2.1.0

### Issue

It is said that SubPageList is compatible with MediaWiki 1.35 (https://github.com/ProfessionalWiki/SubPageList/blob/master/doc/INSTALL.md#platform-compatibility-and-release-status), but is calling a method introduced in MediaWiki 1.36: https://doc.wikimedia.org/mediawiki-core/master/php/classMediaWiki_1_1MediaWikiServices.html#af9ff69eed7556f70aa2d2b2aee7574ef

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

```
MediaWiki internal error.

Original exception: [ZHt27uQZeQokWBLn3SM9SAAAAIs] /bluespice/index.php?title=oldwiki_Namespace:Page Error from line 46 of /var/www/html/bluespice/extensions/SubPageList/src/Lister/UI/HierarchyRendererFactory.php: Call to undefined method MediaWiki\MediaWikiServices::getPageProps()
Backtrace:
#0 /var/www/html/bluespice/extensions/SubPageList/src/Lister/UI/HierarchyRendererFactory.php(39): SubPageList\Lister\UI\HierarchyRendererFactory->newPageRenderer()
#1 /var/www/html/bluespice/extensions/SubPageList/src/Lister/UI/WikitextSubPageListRenderer.php(61): SubPageList\Lister\UI\HierarchyRendererFactory->newTreeListRenderer()
#2 /var/www/html/bluespice/extensions/SubPageList/src/Lister/UI/WikitextSubPageListRenderer.php(42): SubPageList\Lister\UI\WikitextSubPageListRenderer->addPageHierarchy()
#3 /var/www/html/bluespice/extensions/SubPageList/src/Lister/SubPageList.php(125): SubPageList\Lister\UI\WikitextSubPageListRenderer->render()
#4 /var/www/html/bluespice/extensions/SubPageList/src/Lister/SubPageList.php(87): SubPageList\Lister\SubPageList->getRenderedList()
#5 /var/www/html/bluespice/extensions/SubPageList/src/Lister/SubPageList.php(59): SubPageList\Lister\SubPageList->renderForTitle()
#6 /var/www/html/bluespice/vendor/mediawiki/parser-hooks/src/FunctionRunner.php(48): SubPageList\Lister\SubPageList->handle()
#7 /var/www/html/bluespice/vendor/mediawiki/parser-hooks/src/HookRegistrant.php(45): ParserHooks\FunctionRunner->run()
#8 /var/www/html/bluespice/includes/parser/Parser.php(3341): ParserHooks\HookRegistrant->ParserHooks\{closure}()
#9 /var/www/html/bluespice/includes/parser/Parser.php(3048): Parser->callParserFunction()
#10 /var/www/html/bluespice/includes/parser/PPFrame_Hash.php(263): Parser->braceSubstitution()
#11 /var/www/html/bluespice/includes/parser/Parser.php(2888): PPFrame_Hash->expand()
#12 /var/www/html/bluespice/includes/parser/Parser.php(1557): Parser->replaceVariables()
#13 /var/www/html/bluespice/includes/parser/Parser.php(652): Parser->internalParse()
#14 /var/www/html/bluespice/includes/content/WikitextContent.php(374): Parser->parse()
#15 /var/www/html/bluespice/includes/content/AbstractContent.php(590): WikitextContent->fillParserOutput()
#16 /var/www/html/bluespice/includes/Revision/RenderedRevision.php(263): AbstractContent->getParserOutput()
#17 /var/www/html/bluespice/includes/Revision/RenderedRevision.php(235): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached()
#18 /var/www/html/bluespice/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput()
#19 /var/www/html/bluespice/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput()
#20 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}()
#21 /var/www/html/bluespice/includes/Revision/RenderedRevision.php(197): call_user_func()
#22 /var/www/html/bluespice/includes/poolcounter/PoolWorkArticleView.php(216): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#23 /var/www/html/bluespice/includes/poolcounter/PoolCounterWork.php(162): PoolWorkArticleView->doWork()
#24 /var/www/html/bluespice/includes/page/Article.php(810): PoolCounterWork->execute()
#25 /var/www/html/bluespice/includes/actions/ViewAction.php(80): Article->view()
#26 /var/www/html/bluespice/includes/MediaWiki.php(531): ViewAction->show()
#27 /var/www/html/bluespice/includes/MediaWiki.php(313): MediaWiki->performAction()
#28 /var/www/html/bluespice/includes/MediaWiki.php(947): MediaWiki->performRequest()
#29 /var/www/html/bluespice/includes/MediaWiki.php(547): MediaWiki->main()
#30 /var/www/html/bluespice/index.php(53): MediaWiki->run()
#31 /var/www/html/bluespice/index.php(46): wfIndexMain()
#32 {main}

Exception caught inside exception handler: [ZHt27uQZeQokWBLn3SM9SAAAAIs] /bluespice/index.php?title=Namespace:Page Error from line 46 of /var/www/html/bluespice/extensions/SubPageList/src/Lister/UI/HierarchyRendererFactory.php: Call to undefined method MediaWiki\MediaWikiServices::getPageProps()
Backtrace:
#0 /var/www/html/bluespice/extensions/SubPageList/src/Lister/UI/HierarchyRendererFactory.php(39): SubPageList\Lister\UI\HierarchyRendererFactory->newPageRenderer()
#1 /var/www/html/bluespice/extensions/SubPageList/src/Lister/UI/WikitextSubPageListRenderer.php(61): SubPageList\Lister\UI\HierarchyRendererFactory->newTreeListRenderer()
#2 /var/www/html/bluespice/extensions/SubPageList/src/Lister/UI/WikitextSubPageListRenderer.php(42): SubPageList\Lister\UI\WikitextSubPageListRenderer->addPageHierarchy()
#3 /var/www/html/bluespice/extensions/SubPageList/src/Lister/SubPageList.php(125): SubPageList\Lister\UI\WikitextSubPageListRenderer->render()
#4 /var/www/html/bluespice/extensions/SubPageList/src/Lister/SubPageList.php(87): SubPageList\Lister\SubPageList->getRenderedList()
#5 /var/www/html/bluespice/extensions/SubPageList/src/Lister/SubPageList.php(59): SubPageList\Lister\SubPageList->renderForTitle()
#6 /var/www/html/bluespice/vendor/mediawiki/parser-hooks/src/FunctionRunner.php(48): SubPageList\Lister\SubPageList->handle()
#7 /var/www/html/bluespice/vendor/mediawiki/parser-hooks/src/HookRegistrant.php(45): ParserHooks\FunctionRunner->run()
#8 /var/www/html/bluespice/includes/parser/Parser.php(3341): ParserHooks\HookRegistrant->ParserHooks\{closure}()
#9 /var/www/html/bluespice/includes/parser/Parser.php(3048): Parser->callParserFunction()
#10 /var/www/html/bluespice/includes/parser/PPFrame_Hash.php(263): Parser->braceSubstitution()
#11 /var/www/html/bluespice/includes/parser/Parser.php(2888): PPFrame_Hash->expand()
#12 /var/www/html/bluespice/includes/parser/Parser.php(928): Parser->replaceVariables()
#13 /var/www/html/bluespice/extensions/BlueSpiceFoundation/includes/utility/PageContentProvider.class.php(162): Parser->preprocess()
#14 /var/www/html/bluespice/extensions/BlueSpiceFoundation/includes/utility/PageContentProvider.class.php(429): BsPageContentProvider->getContentFromRevision()
#15 /var/www/html/bluespice/extensions/BlueSpiceFoundation/includes/utility/PageContentProvider.class.php(401): BsPageContentProvider->getWikiTextContentForArticle()
#16 /var/www/html/bluespice/extensions/BlueSpiceBookshelf/src/PageHierarchyProviderFactory.php(54): BsPageContentProvider->getWikiTextContentFor()
#17 /var/www/html/bluespice/extensions/BlueSpiceBookshelf/includes/PageHierarchyProvider.php(92): BlueSpice\Bookshelf\PageHierarchyProviderFactory->getInstanceForArticle()
#18 /var/www/html/bluespice/extensions/BlueSpiceUEModuleBookPDF/src/ExportDialogPluginBook.php(97): PageHierarchyProvider::getInstanceForArticle()
#19 /var/www/html/bluespice/extensions/BlueSpiceUniversalExport/src/ExportDialogButtonComponent.php(63): BlueSpice\UEModuleBookPDF\ExportDialogPluginBook->skip()
#20 /var/www/html/bluespice/vendor/mwstake/mediawiki-component-commonuserinterface/src/ComponentFilter/DefaultFilter.php(13): BlueSpice\UniversalExport\ExportDialogButtonComponent->shouldRender()
#21 /var/www/html/bluespice/vendor/mwstake/mediawiki-component-commonuserinterface/src/ComponentManager.php(225): MWStake\MediaWiki\Component\CommonUserInterface\ComponentFilter\DefaultFilter->shouldRender()
#22 /var/www/html/bluespice/vendor/mwstake/mediawiki-component-commonuserinterface/src/ComponentManager.php(186): MWStake\MediaWiki\Component\CommonUserInterface\ComponentManager->processComponent()
#23 /var/www/html/bluespice/vendor/mwstake/mediawiki-component-commonuserinterface/src/ComponentManager.php(120): MWStake\MediaWiki\Component\CommonUserInterface\ComponentManager->init()
#24 /var/www/html/bluespice/vendor/mwstake/mediawiki-component-commonuserinterface/includes/ServiceWiring.php(31): MWStake\MediaWiki\Component\CommonUserInterface\ComponentManager::singleton()
#25 /var/www/html/bluespice/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer->{closure}()
#26 /var/www/html/bluespice/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService()
#27 /var/www/html/bluespice/vendor/mwstake/mediawiki-component-commonuserinterface/src/Setup.php(56): Wikimedia\Services\ServiceContainer->getService()
#28 /var/www/html/bluespice/includes/HookContainer/HookContainer.php(329): MWStake\MediaWiki\Component\CommonUserInterface\Setup::onBeforePageDisplay()
#29 /var/www/html/bluespice/includes/HookContainer/HookContainer.php(132): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#30 /var/www/html/bluespice/includes/HookContainer/HookRunner.php(991): MediaWiki\HookContainer\HookContainer->run()
#31 /var/www/html/bluespice/includes/OutputPage.php(2619): MediaWiki\HookContainer\HookRunner->onBeforePageDisplay()
#32 /var/www/html/bluespice/includes/exception/MWExceptionRenderer.php(153): OutputPage->output()
#33 /var/www/html/bluespice/includes/exception/MWExceptionRenderer.php(65): MWExceptionRenderer::reportHTML()
#34 /var/www/html/bluespice/includes/exception/MWExceptionHandler.php(106): MWExceptionRenderer::output()
#35 /var/www/html/bluespice/includes/exception/MWExceptionHandler.php(185): MWExceptionHandler::report()
#36 /var/www/html/bluespice/includes/MediaWiki.php(583): MWExceptionHandler::handleException()
#37 /var/www/html/bluespice/index.php(53): MediaWiki->run()
#38 /var/www/html/bluespice/index.php(46): wfIndexMain()
#39 {main}
```

Steps to reproduce the observation on a public wiki if possible:

Install on 1.35.10 and insert `{{#subpages: }}` to a page.

**Comment by kghbln** [comment]
Thanks for bringing this to our attention. This indeed slipped. You will have to go back to the 2.0.x branch. @JeroenDeDauw Ouch, [this](https://github.com/ProfessionalWiki/SubPageList/pull/71) should have been a 3.0 release. How to fix best. Do another release as 3.0 with updated docu and corrected extension.json?!

**Comment by JeroenDeDauw** [comment]
@kghbln Sure

@markus-96 you'll have to stick with version 2.0.2

**Comment by kghbln** [comment]
https://github.com/ProfessionalWiki/SubPageList/pull/73
