### ISSUE TITLE
MediaWiki 1.43 compatibility

### ISSUE THREAD

**Issue by osnard** [ProfessionalWiki/SubPageList#76]
### Setup

- MediaWiki version: 1.43 (pre-release)
- PHP version: 8.1
- Database and version (MySQL etc.): MariaDB 10
- SubPageList version: 3.0.0

### Issue

Access to $wgHooks as an array is not possible anymore in MediaWiki 1.43

```
[202105fb517a088fb45d9d57] /w/index.php?title=Main_Page TypeError: SubPageList\Setup::__construct(): Argument #2 ($hooks) must be of type array, MediaWiki\HookContainer\FauxGlobalHookArray given, called in extensions/SubPageList/src/Setup.php on line 57

Backtrace:

from extensions/SubPageList/src/Setup.php(44)
#0 extensions/SubPageList/src/Setup.php(57): SubPageList\Setup->__construct(SubPageList\Extension, MediaWiki\HookContainer\FauxGlobalHookArray, string)
#1 includes/Setup.php(575): SubPageList\Setup::onExtensionFunctions()
#2 includes/WebStart.php(85): require_once(string)
#3 index.php(50): require(string)
#4 {main}
```

**Comment by osnard** [comment]
Looks like there is more to do
```
[e8e4a4988658f1ac410dacab] [no req]   Error: Class "TitleArray" not found
Backtrace:
from extensions/SubPageList/src/Lister/SimpleSubPageFinder.php(142)
#0 extensions/SubPageList/src/Lister/SubPageList.php(105): SubPageList\Lister\SimpleSubPageFinder->getSubPagesFor(MediaWiki\Title\Title)
#1 extensions/SubPageList/src/Lister/SubPageList.php(81): SubPageList\Lister\SubPageList->getPageHierarchy(MediaWiki\Title\Title, string, int, bool)
#2 extensions/SubPageList/src/Lister/SubPageList.php(59): SubPageList\Lister\SubPageList->renderForTitle(MediaWiki\Title\Title, array)
#3 vendor/mediawiki/parser-hooks/src/FunctionRunner.php(48): SubPageList\Lister\SubPageList->handle(MediaWiki\Parser\Parser, ParamProcessor\ProcessingResult)
#4 vendor/mediawiki/parser-hooks/src/HookRegistrant.php(45): ParserHooks\FunctionRunner->run(MediaWiki\Parser\Parser, array, PPFrame_Hash)
#5 includes/parser/Parser.php(3463): ParserHooks\HookRegistrant->ParserHooks\{closure}(MediaWiki\Parser\Parser, PPFrame_Hash, array)
#6 includes/parser/Parser.php(3146): MediaWiki\Parser\Parser->callParserFunction(PPFrame_Hash, string, array)
#7 includes/parser/PPFrame_Hash.php(276): MediaWiki\Parser\Parser->braceSubstitution(array, PPFrame_Hash)
#8 includes/parser/PPTemplateFrame_Hash.php(178): PPFrame_Hash->expand(PPNode_Hash_Tree, int)
#9 includes/parser/PPTemplateFrame_Hash.php(190): PPTemplateFrame_Hash->getNamedArgument(string)
#10 includes/parser/Parser.php(3944): PPTemplateFrame_Hash->getArgument(string)
#11 includes/parser/PPFrame_Hash.php(293): MediaWiki\Parser\Parser->argSubstitution(array, PPTemplateFrame_Hash)
#12 includes/parser/Parser.php(3337): PPFrame_Hash->expand(PPNode_Hash_Tree)
#13 includes/parser/PPFrame_Hash.php(276): MediaWiki\Parser\Parser->braceSubstitution(array, PPFrame_Hash)
#14 includes/parser/Parser.php(2980): PPFrame_Hash->expand(PPNode_Hash_Tree, int)
#15 includes/parser/Parser.php(1626): MediaWiki\Parser\Parser->replaceVariables(string)
#16 includes/parser/Parser.php(728): MediaWiki\Parser\Parser->internalParse(string)
#17 includes/content/WikitextContentHandler.php(381): MediaWiki\Parser\Parser->parse(string, MediaWiki\Title\Title, ParserOptions, bool, bool, null)
#18 includes/content/ContentHandler.php(1693): MediaWiki\Content\WikitextContentHandler->fillParserOutput(MediaWiki\Content\WikitextContent, MediaWiki\Content\Renderer\ContentParseParams, MediaWiki\Parser\ParserOutput)
#19 includes/content/Renderer/ContentRenderer.php(67): MediaWiki\Content\ContentHandler->getParserOutput(MediaWiki\Content\WikitextContent, MediaWiki\Content\Renderer\ContentParseParams)
#20 includes/Revision/RenderedRevision.php(260): MediaWiki\Content\Renderer\ContentRenderer->getParserOutput(MediaWiki\Content\WikitextContent, MediaWiki\Title\Title, MediaWiki\Revision\MutableRevisionRecord, ParserOptions, bool)
#21 includes/Revision/RenderedRevision.php(232): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(MediaWiki\Content\WikitextContent, bool)
#22 includes/Revision/RevisionRenderer.php(226): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string, array)
#23 includes/Revision/RevisionRenderer.php(164): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, ParserOptions, array)
#24 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#25 includes/Revision/RenderedRevision.php(199): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#26 extensions/TemplateData/includes/Hooks.php(116): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput(array)
#27 includes/HookContainer/HookContainer.php(159): MediaWiki\Extension\TemplateData\Hooks->onMultiContentSave(MediaWiki\Revision\RenderedRevision, MediaWiki\User\User, MediaWiki\CommentStore\CommentStoreComment, int, MediaWiki\Storage\PageUpdateStatus)
#28 includes/HookContainer/HookRunner.php(2638): MediaWiki\HookContainer\HookContainer->run(string, array)
#29 includes/Storage/PageUpdater.php(894): MediaWiki\HookContainer\HookRunner->onMultiContentSave(MediaWiki\Revision\RenderedRevision, MediaWiki\User\User, MediaWiki\CommentStore\CommentStoreComment, int, MediaWiki\Storage\PageUpdateStatus)
...
#40 {main}
```

Will try to provide a patch as well.
